excel family scripts

diff --git a/src/excel_tocsv b/src/excel_tocsv
--- a/src/excel_tocsv
+++ b/src/excel_tocsv
@@ -1,4 +1,4 @@
-#!/bin/ksh
+#! /bin/ksh
 
 #
 #
@@ -22,43 +22,47 @@
 #
 #
 
-if ! utilchk 'pdfinfo' 'qpdf' 'exiftool'
+if ! utilchk ssconvert
 then
 
-  printf "There are utilities missing to run this script\n" >&2
+  printf "Missing utility\n" >&2
   exit 1
 
 fi
 
-if (( "$#" != 0 ))
+if (( $# != 1 ))
 then
 
-  printf "This program does not take any arguments\n" >&2
-  printf "It runs in current directory\n" >&2
+  printf "This program expects one argument\n" >&2
+  printf "Excel file to convert\n" >&2
   exit 1
 
 fi
 
+if ! test -e "$1"
 
-tf="$( mktemp )"
-tf2="$( mktemp )"
-tf3="$( mktemp )"
+  printf "Specified file does not exist\n" >&2
+  exit 2
 
-find . -type f -iname '*.pdf' > "$tf"
+then
 
-while IFS= read -r pdffile
-do
+if ! test -f "$1"
 
-  printf "PDF file: %s\n" "$pdffile"
-  pdfinfo "$pdffile"
+  printf "Specified file is not regular file\n" >&2
+  exit 2
 
-  qpdf "$pdffile" "$tf2"
-  exiftool '-all:all=' "$tf2"
-  qpdf "$tf2" "$tf3"
-  mv "$tf3" "$pdffile"
+then
 
-  pdfinfo "$pdffile"
+newname="${1%.*}"'.csv'
+  
+if test -e "$newname"
+then
 
-done < "$tf"
+  printf "File %s already exists\n" "$newname" >&2
+  exit 4 
 
-rm -f "$tf" "$tf2" "$tf3"
+fi
+
+! ssconvert "$file" "$newname" && exit 3
+pritnf "%s -> %s\n" "$file" "$newname"
+
diff --git a/src/excel_tocsv_dir b/src/excel_tocsv_dir
--- a/src/excel_tocsv_dir
+++ b/src/excel_tocsv_dir
@@ -22,29 +22,47 @@
 #
 #
 
+if ! utilchk ssconvert
+then
 
+  printf "Missing utility\n" >&2
+  exit 1
+
+fi
+
+csvfile_existed=0
 tempfile="$( mktemp )"
 
-find . -maxdepth 1 -type f > "$tempfile"
+find . -maxdepth 1 -type f\
+  \( -iname '*.xlw' -o -iname '*.xls' -o -iname '*.xlsx' \)\
+  > "$tempfile"
 
 while IFS= read -r file
 do
 
-  if [[ "$file" == *'.xls' ]]
+  newname="${file%.*}"'.csv'
+  
+  if test -e "$newname"
   then
 
-    newname=${file%.*}'.csv'
-    if test -e "$newname"
-    then
-	    printf "File %s already exists\n" "$newname" >&2
-	    continue
-    fi
-    ssconvert "$file" "$newname"
-    pritnf "%s -> %s\n" "$file" "$newname"
-    rm -f "$file"
+    printf "File %s already exists\n" "$newname" >&2
+    csvfile_existed=1
+    continue
 
   fi
+
+  ! ssconvert "$file" "$newname" && exit 3
+  pritnf "%s -> %s\n" "$file" "$newname"
 
 done < "$tempfile"
 
 rm -f "$tempfile"
+
+if (( csvfile_existed ))
+then
+
+  printf "Some csv files already existed,\n" >&2
+  printf  "program did not overwrite them\n" >&2
+  exit 4
+
+fi
diff --git a/src/excel_tocsv_rdir b/src/excel_tocsv_rdir
--- a/src/excel_tocsv_rdir
+++ b/src/excel_tocsv_rdir
@@ -1,8 +1,8 @@
-#!/bin/ksh
+#! /bin/ksh
 
 #
 #
-# Copyright (c) 2021 Piotr Trzpil  p.trzpil@protonmail.com
+# Copyright (c) 2023 Piotr Trzpil  p.trzpil@protonmail.com
 #
 # Permission to use, copy, modify, and distribute 
 # this software for any purpose with or without fee
@@ -22,52 +22,47 @@
 #
 #
 
-
-if test -z "$1"
+if ! utilchk ssconvert
 then
-	printf "Need argument to erase from input form\n" 1>&2 
-	exit
+
+  printf "Missing utility\n" >&2
+  exit 1
+
 fi
 
-first=1
-found=0
-ampersand=0;
+csvfile_existed=0
+tempfile="$( mktemp )"
 
+find . -type f\
+  \( -iname '*.xlw' -o -iname '*.xls' -o -iname '*.xlsx' \)\
+  > "$tempfile"
 
-while IFS= read -r line
+while IFS= read -r file
 do
 
-  if (( "$found" == 0 ))
+  newname="${file%.*}"'.csv'
+  
+  if test -e "$newname"
   then
- 	if [ "$line" == "$1" ]
-	then
-		read -r line
-	  	read -r line
-	  	found=1;
-	  	continue
-  	fi
+
+    printf "File %s already exists\n" "$newname" >&2
+    csvfile_existed=1
+    continue
+
   fi
 
-  if [[ "$line" == '&' ]]
-  then
-	  ampersand=1
-	  continue;
-  fi
+  ! ssconvert "$file" "$newname" && exit 3
+  pritnf "%s -> %s\n" "$file" "$newname"
 
-  if (( ampersand == 1 ))
-  then
-	  if (( "$first" == 0 ))
-	  then
-		ampersand=0
-	  	printf "&\n"
-	  else
-		ampersand=0
-	  fi
-  fi
+done < "$tempfile"
 
-  first=0
-  printf "%s\n" "$line"
+rm -f "$tempfile"
 
-done
+if (( csvfile_existed ))
+then
 
+  printf "Some csv files already existed,\n" >&2
+  printf  "program did not overwrite them\n" >&2
+  exit 4
 
+fi
