i dont even know where I ended been so long, just saving stuff, need to make lext better, so probably recode a lot in smallsoft

diff --git a/src/html_gettag b/src/html_gettag
--- a/src/html_gettag
+++ b/src/html_gettag
@@ -2,7 +2,7 @@
 
 #
 #
-# Copyright (c) 2021-2023 Piotr Trzpil  p.trzpil@protonmail.com
+# Copyright (c) 2021 Piotr Trzpil  p.trzpil@protonmail.com
 #
 # Permission to use, copy, modify, and distribute 
 # this software for any purpose with or without fee
@@ -22,19 +22,24 @@
 #
 #
 
+# lext need to be more powerful
 
-if ! utilchk 'mpd' 'mpc'
+if ! utilchk 'htmlentities' 'fext'
 then
 
-  printf "Missing utilities\n" >&2
+  printf "Missing utility\n" >&2
   exit 1
 
 fi
 
-var="$( mpc listall | \
-	awk -F'/' '{ print $NF }' | \
-       	grep -Fin "$1" )"
-var="${var%%:*}"
-mpc play "$var"
+tmp="$( mktemp )"
+cat > "$tmp"
 
+ans="$( lext -c 'form action="' '"' < "$tmp" | htmlentities -d )"
+if test -z "$ans"
+then
+	ans="$( lext -c 'form action=' ' ' < "$tmp" | htmlentities -d )"
+fi
 
+printf "%s" "$ans"
+rm -f "$tmp"
