minorfixes and options detector

diff --git a/src/ksh_opts b/src/ksh_opts
--- a/src/ksh_opts
+++ b/src/ksh_opts
@@ -2,7 +2,7 @@
 
 #
 #
-# Copyright (c) 2021-2023 Piotr Trzpil  p.trzpil@protonmail.com
+# Copyright (c) 2023 Piotr Trzpil  p.trzpil@protonmail.com
 #
 # Permission to use, copy, modify, and distribute 
 # this software for any purpose with or without fee
@@ -23,18 +23,15 @@
 #
 
 
-if ! utilchk 'mpd' 'mpc'
+
+if ! utilchk 'sh_getopt'
 then
 
-  printf "Missing utilities\n" >&2
+  printf "Missing utilities.\n" >&2
   exit 1
 
 fi
 
-var="$( mpc listall | \
-	awk -F'/' '{ print $NF }' | \
-       	grep -Fin "$1" )"
-var="${var%%:*}"
-mpc play "$var"
+
 
 
