new scripts, nice update

diff --git a/src/mpd_play b/src/mpd_play
--- a/src/mpd_play
+++ b/src/mpd_play
@@ -2,7 +2,7 @@
 
 #
 #
-# Copyright (c) 2021 Piotr Trzpil  p.trzpil@protonmail.com
+# Copyright (c) 2021-2023 Piotr Trzpil  p.trzpil@protonmail.com
 #
 # Permission to use, copy, modify, and distribute 
 # this software for any purpose with or without fee
@@ -23,6 +23,13 @@
 #
 
 
+if ! utilchk 'mpd' 'mpc'
+then
+
+  printf "Missing utilities\n" >&2
+  exit 1
+
+fi
 
 var="$( mpc listall | \
 	awk -F'/' '{ print $NF }' | \
